# Generated by Django 2.2 on 2019-05-24 21:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=225, unique=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='HumanName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'human_name',
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Borrow', 'Borrow'), ('Lend', 'Lend'), ('Done', 'Done')], max_length=20, verbose_name='state')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Date')),
                ('money', models.IntegerField(help_text='JPY', verbose_name='Amount')),
                ('memo', models.CharField(max_length=500, verbose_name='Memo')),
                ('deadline', models.DateField(blank=True, default=None, null=True, verbose_name='Deadline')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moneyrecord.Category', verbose_name='Category')),
                ('human_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moneyrecord.HumanName', verbose_name='Name')),
            ],
            options={
                'db_table': 'list',
            },
        ),
    ]
